spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/musicat?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: ssafy
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show-sql: true
